name: Execute Build

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: npm ci && npx vite build
        working-directory: src
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist