name: Deploy static content to Pages

on:
  push:
    branches: ['master']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Orbits Install dependencies
        run: npm install
        working-directory: orbits
      - name: Orbits Build
        run: npx vite build
        working-directory: orbits
      - name: recBubbles Install dependencies
        run: npm install
        working-directory: recBubbles
      - name: recBubbles Build
        run: npx vite build
        working-directory: recBubbles
      - name: balls Install dependencies
        run: npm install
        working-directory: balls
      - name: balls Build
        run: npx vite build
        working-directory: balls
      - name: fireWorks Install dependencies
        run: npm install
        working-directory: fireWorks
      - name: fireWorks Build
        run: npx vite build
        working-directory: fireWorks
      - name: Move index
        run: cp index.html dist/
      - name: Move overview images
        run: mkdir -p dist/img && cp img/* dist/img
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/deploy-pages@v4
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2